# coding: utf-8

"""
    Tango Card RaaS API

    <p>Welcome to the RaaS&reg; API – with this RESTful API you can integrate a global reward or incentive program into your app or platform.<br /><br /> This console works in our Sandbox environment. To receive your own credentials or to ask questions, please contact us at <a href=\"mailto:devsupport@tangocard.com\">devsupport@tangocard.com</a>.  # noqa: E501

    OpenAPI spec version: 2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import tango_client
from tango_client.api.3__fund_api import 3FundApi  # noqa: E501
from tango_client.rest import ApiException


class Test3FundApi(unittest.TestCase):
    """3FundApi unit test stubs"""

    def setUp(self):
        self.api = tango_client.api.3__fund_api.3FundApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_credit_card(self):
        """Test case for create_credit_card

        Register a new Credit Card.  # noqa: E501
        """
        pass

    def test_create_credit_card_deposit(self):
        """Test case for create_credit_card_deposit

        Fund an Account.  # noqa: E501
        """
        pass

    def test_create_credit_card_unregister(self):
        """Test case for create_credit_card_unregister

        Unregister a Credit Card.  # noqa: E501
        """
        pass

    def test_get_credit_card(self):
        """Test case for get_credit_card

        Get details for a specific Credit Card.  # noqa: E501
        """
        pass

    def test_get_credit_card_deposit(self):
        """Test case for get_credit_card_deposit

        Get details for a specific Credit Card Deposit.  # noqa: E501
        """
        pass

    def test_list_credit_cards(self):
        """Test case for list_credit_cards

        List all credit cards registered on this Platform.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
