# coding: utf-8

"""
    Tango Card RaaS API

    <p>Welcome to the RaaS&reg; API – with this RESTful API you can integrate a global reward or incentive program into your app or platform.<br /><br /> This console works in our Sandbox environment. To receive your own credentials or to ask questions, please contact us at <a href=\"mailto:devsupport@tangocard.com\">devsupport@tangocard.com</a>.  # noqa: E501

    OpenAPI spec version: 2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import tango_client
from tango_client.api.7__exchange_rates_api import 7ExchangeRatesApi  # noqa: E501
from tango_client.rest import ApiException


class Test7ExchangeRatesApi(unittest.TestCase):
    """7ExchangeRatesApi unit test stubs"""

    def setUp(self):
        self.api = tango_client.api.7__exchange_rates_api.7ExchangeRatesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_exchange_rates(self):
        """Test case for get_exchange_rates

        Get a list of exchange rates.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
