# coding: utf-8

"""
    Tango Card RaaS API

    <p>Welcome to the RaaS&reg; API – with this RESTful API you can integrate a global reward or incentive program into your app or platform.<br /><br /> This console works in our Sandbox environment. To receive your own credentials or to ask questions, please contact us at <a href=\"mailto:devsupport@tangocard.com\">devsupport@tangocard.com</a>.  # noqa: E501

    OpenAPI spec version: 2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import tango_client
from tango_client.api.1__customers_api import 1CustomersApi  # noqa: E501
from tango_client.rest import ApiException


class Test1CustomersApi(unittest.TestCase):
    """1CustomersApi unit test stubs"""

    def setUp(self):
        self.api = tango_client.api.1__customers_api.1CustomersApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_customer(self):
        """Test case for create_customer

        Create a new Customer on this Platform.  # noqa: E501
        """
        pass

    def test_create_customer_account(self):
        """Test case for create_customer_account

        Create an Account under a specific Customer on this Platform.  # noqa: E501
        """
        pass

    def test_get_customer(self):
        """Test case for get_customer

        Get details for a specific Customer on this Platform.  # noqa: E501
        """
        pass

    def test_list_customer_accounts1(self):
        """Test case for list_customer_accounts1

        Get a list of all Accounts created for a specific Customer on this Platform.  # noqa: E501
        """
        pass

    def test_list_customers(self):
        """Test case for list_customers

        Get a list of all Customers on this Platform.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
