# coding: utf-8

"""
    Tango Card RaaS API

    <p>Welcome to the RaaS&reg; API – with this RESTful API you can integrate a global reward or incentive program into your app or platform.<br /><br /> This console works in our Sandbox environment. To receive your own credentials or to ask questions, please contact us at <a href=\"mailto:devsupport@tangocard.com\">devsupport@tangocard.com</a>.  # noqa: E501

    OpenAPI spec version: 2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import tango_client
from tango_client.api.5__orders_api import 5OrdersApi  # noqa: E501
from tango_client.rest import ApiException


class Test5OrdersApi(unittest.TestCase):
    """5OrdersApi unit test stubs"""

    def setUp(self):
        self.api = tango_client.api.5__orders_api.5OrdersApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_order(self):
        """Test case for create_order

        Create an Order under a specific Account.  # noqa: E501
        """
        pass

    def test_get_order(self):
        """Test case for get_order

        Get details for a specific Order.  # noqa: E501
        """
        pass

    def test_get_order_resends(self):
        """Test case for get_order_resends

        Resend a specific Order.  # noqa: E501
        """
        pass

    def test_list_orders(self):
        """Test case for list_orders

        Get a list of Orders placed under this Platform.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
