# coding: utf-8

"""
    Tango Card RaaS API

    <p>Welcome to the RaaS&reg; API – with this RESTful API you can integrate a global reward or incentive program into your app or platform.<br /><br /> This console works in our Sandbox environment. To receive your own credentials or to ask questions, please contact us at <a href=\"mailto:devsupport@tangocard.com\">devsupport@tangocard.com</a>.  # noqa: E501

    OpenAPI spec version: 2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import tango_client
from tango_client.models.item_view_verbose import ItemViewVerbose  # noqa: E501
from tango_client.rest import ApiException


class TestItemViewVerbose(unittest.TestCase):
    """ItemViewVerbose unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testItemViewVerbose(self):
        """Test ItemViewVerbose"""
        # FIXME: construct object with mandatory attributes with example values
        # model = tango_client.models.item_view_verbose.ItemViewVerbose()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
