# coding: utf-8

"""
    Tango Card RaaS API

    <p>Welcome to the RaaS&reg; API – with this RESTful API you can integrate a global reward or incentive program into your app or platform.<br /><br /> This console works in our Sandbox environment. To receive your own credentials or to ask questions, please contact us at <a href=\"mailto:devsupport@tangocard.com\">devsupport@tangocard.com</a>.  # noqa: E501

    OpenAPI spec version: 2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import tango_client
from tango_client.api.6__email_templates_api import 6EmailTemplatesApi  # noqa: E501
from tango_client.rest import ApiException


class Test6EmailTemplatesApi(unittest.TestCase):
    """6EmailTemplatesApi unit test stubs"""

    def setUp(self):
        self.api = tango_client.api.6__email_templates_api.6EmailTemplatesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_email_template(self):
        """Test case for create_email_template

        Create a new email template  # noqa: E501
        """
        pass

    def test_delete_email_template(self):
        """Test case for delete_email_template

        Delete a specific Email Template on this Platform.  # noqa: E501
        """
        pass

    def test_get_email_template(self):
        """Test case for get_email_template

        Get details for a specific Email Template on this Platform.  # noqa: E501
        """
        pass

    def test_list_email_templates(self):
        """Test case for list_email_templates

        Get a list of all Email Templates on this Platform.  # noqa: E501
        """
        pass

    def test_update_email_template(self):
        """Test case for update_email_template

        Update details for a specific Email Template on this Platform.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
