# coding: utf-8

"""
    Tango Card RaaS API

    <p>Welcome to the RaaS&reg; API – with this RESTful API you can integrate a global reward or incentive program into your app or platform.<br /><br /> This console works in our Sandbox environment. To receive your own credentials or to ask questions, please contact us at <a href=\"mailto:devsupport@tangocard.com\">devsupport@tangocard.com</a>.  # noqa: E501

    OpenAPI spec version: 2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import tango_client
from tango_client.api.2__accounts_api import 2AccountsApi  # noqa: E501
from tango_client.rest import ApiException


class Test2AccountsApi(unittest.TestCase):
    """2AccountsApi unit test stubs"""

    def setUp(self):
        self.api = tango_client.api.2__accounts_api.2AccountsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_account(self):
        """Test case for get_account

        Get details for a specific Account on this Platform.  # noqa: E501
        """
        pass

    def test_list_customer_accounts(self):
        """Test case for list_customer_accounts

        Get a list of Accounts created on this Platform.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
