# coding: utf-8

# flake8: noqa
"""
    Tango Card RaaS API

    <5. Ordersp>Welcome to the RaaS&reg; API – with this RESTful API you can integrate a global reward or incentive program into your app or platform.<br /><br /> This console works in our Sandbox environment. To receive your own credentials or to ask questions, please contact us at <a href=\"mailto:devsupport@tangocard.com\">devsupport@tangocard.com</a>.  # noqa: E501

    OpenAPI spec version: 2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

# import models into model package
from tango_client.models.account_view import AccountView
from tango_client.models.account_view_summary import AccountViewSummary
from tango_client.models.billing_address_criteria import BillingAddressCriteria
from tango_client.models.brand_requirements import BrandRequirements
from tango_client.models.brand_view_with_items_verbose import BrandViewWithItemsVerbose
from tango_client.models.catalog_view import CatalogView
from tango_client.models.catalog_view_verbose import CatalogViewVerbose
from tango_client.models.contact_information_criteria import ContactInformationCriteria
from tango_client.models.contact_information_view import ContactInformationView
from tango_client.models.cost_adjustment_entity import CostAdjustmentEntity
from tango_client.models.create_account_criteria import CreateAccountCriteria
from tango_client.models.create_credit_card_criteria import CreateCreditCardCriteria
from tango_client.models.create_credit_card_deposit_criteria import CreateCreditCardDepositCriteria
from tango_client.models.create_credit_card_unregister_criteria import CreateCreditCardUnregisterCriteria
from tango_client.models.create_customer_criteria import CreateCustomerCriteria
from tango_client.models.create_email_template_criteria import CreateEmailTemplateCriteria
from tango_client.models.create_order_criteria import CreateOrderCriteria
from tango_client.models.credential_view import CredentialView
from tango_client.models.credit_card_criteria import CreditCardCriteria
from tango_client.models.credit_card_deposit_view import CreditCardDepositView
from tango_client.models.credit_card_unregister_view import CreditCardUnregisterView
from tango_client.models.credit_card_view import CreditCardView
from tango_client.models.customer_view import CustomerView
from tango_client.models.customer_view_new import CustomerViewNew
from tango_client.models.customer_view_summary import CustomerViewSummary
from tango_client.models.email_template_list_view import EmailTemplateListView
from tango_client.models.email_template_view_verbose import EmailTemplateViewVerbose
from tango_client.models.exchange_rate_view import ExchangeRateView
from tango_client.models.exchange_rates_with_disclaimer import ExchangeRatesWithDisclaimer
from tango_client.models.item_view_verbose import ItemViewVerbose
from tango_client.models.money_view import MoneyView
from tango_client.models.order_list_item_view import OrderListItemView
from tango_client.models.order_list_view import OrderListView
from tango_client.models.order_resend_request_criteria import OrderResendRequestCriteria
from tango_client.models.order_view import OrderView
from tango_client.models.order_view_summary import OrderViewSummary
from tango_client.models.order_view_verbose import OrderViewVerbose
from tango_client.models.page_view import PageView
from tango_client.models.recipient_info_criteria import RecipientInfoCriteria
from tango_client.models.recipient_info_view import RecipientInfoView
from tango_client.models.resend_view import ResendView
from tango_client.models.reward_view import RewardView
from tango_client.models.sender_info_criteria import SenderInfoCriteria
from tango_client.models.sender_info_view import SenderInfoView
from tango_client.models.standard_reward_email_template_access import StandardRewardEmailTemplateAccess
from tango_client.models.standard_reward_email_template_default import StandardRewardEmailTemplateDefault
from tango_client.models.update_email_template_criteria import UpdateEmailTemplateCriteria
