# coding: utf-8

"""
    Tango Card RaaS API

    <p>Welcome to the RaaS&reg; API – with this RESTful API you can integrate a global reward or incentive program into your app or platform.<br /><br /> This console works in our Sandbox environment. To receive your own credentials or to ask questions, please contact us at <a href=\"mailto:devsupport@tangocard.com\">devsupport@tangocard.com</a>.  # noqa: E501

    OpenAPI spec version: 2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from tango_client.configuration import Configuration


class CatalogViewVerbose(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'brands': 'list[BrandViewWithItemsVerbose]',
        'catalog_name': 'str'
    }

    attribute_map = {
        'brands': 'brands',
        'catalog_name': 'catalogName'
    }

    def __init__(self, brands=None, catalog_name=None, _configuration=None):  # noqa: E501
        """CatalogViewVerbose - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._brands = None
        self._catalog_name = None
        self.discriminator = None

        self.brands = brands
        self.catalog_name = catalog_name

    @property
    def brands(self):
        """Gets the brands of this CatalogViewVerbose.  # noqa: E501

        List of Brands inside of this Catalog  # noqa: E501

        :return: The brands of this CatalogViewVerbose.  # noqa: E501
        :rtype: list[BrandViewWithItemsVerbose]
        """
        return self._brands

    @brands.setter
    def brands(self, brands):
        """Sets the brands of this CatalogViewVerbose.

        List of Brands inside of this Catalog  # noqa: E501

        :param brands: The brands of this CatalogViewVerbose.  # noqa: E501
        :type: list[BrandViewWithItemsVerbose]
        """
        if self._configuration.client_side_validation and brands is None:
            raise ValueError("Invalid value for `brands`, must not be `None`")  # noqa: E501

        self._brands = brands

    @property
    def catalog_name(self):
        """Gets the catalog_name of this CatalogViewVerbose.  # noqa: E501

        Catalog Name  # noqa: E501

        :return: The catalog_name of this CatalogViewVerbose.  # noqa: E501
        :rtype: str
        """
        return self._catalog_name

    @catalog_name.setter
    def catalog_name(self, catalog_name):
        """Sets the catalog_name of this CatalogViewVerbose.

        Catalog Name  # noqa: E501

        :param catalog_name: The catalog_name of this CatalogViewVerbose.  # noqa: E501
        :type: str
        """
        if self._configuration.client_side_validation and catalog_name is None:
            raise ValueError("Invalid value for `catalog_name`, must not be `None`")  # noqa: E501

        self._catalog_name = catalog_name

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(CatalogViewVerbose, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, CatalogViewVerbose):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, CatalogViewVerbose):
            return True

        return self.to_dict() != other.to_dict()
