# coding: utf-8

"""
    Tango Card RaaS API

    <p>Welcome to the RaaS&reg; API – with this RESTful API you can integrate a global reward or incentive program into your app or platform.<br /><br /> This console works in our Sandbox environment. To receive your own credentials or to ask questions, please contact us at <a href=\"mailto:devsupport@tangocard.com\">devsupport@tangocard.com</a>.  # noqa: E501

    OpenAPI spec version: 2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from tango_client.configuration import Configuration


class CreateCreditCardUnregisterCriteria(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'account_identifier': 'str',
        'credit_card_token': 'str',
        'customer_identifier': 'str'
    }

    attribute_map = {
        'account_identifier': 'accountIdentifier',
        'credit_card_token': 'creditCardToken',
        'customer_identifier': 'customerIdentifier'
    }

    def __init__(self, account_identifier=None, credit_card_token=None, customer_identifier=None, _configuration=None):  # noqa: E501
        """CreateCreditCardUnregisterCriteria - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._account_identifier = None
        self._credit_card_token = None
        self._customer_identifier = None
        self.discriminator = None

        self.account_identifier = account_identifier
        self.credit_card_token = credit_card_token
        self.customer_identifier = customer_identifier

    @property
    def account_identifier(self):
        """Gets the account_identifier of this CreateCreditCardUnregisterCriteria.  # noqa: E501

        Account Identifier  # noqa: E501

        :return: The account_identifier of this CreateCreditCardUnregisterCriteria.  # noqa: E501
        :rtype: str
        """
        return self._account_identifier

    @account_identifier.setter
    def account_identifier(self, account_identifier):
        """Sets the account_identifier of this CreateCreditCardUnregisterCriteria.

        Account Identifier  # noqa: E501

        :param account_identifier: The account_identifier of this CreateCreditCardUnregisterCriteria.  # noqa: E501
        :type: str
        """
        if self._configuration.client_side_validation and account_identifier is None:
            raise ValueError("Invalid value for `account_identifier`, must not be `None`")  # noqa: E501

        self._account_identifier = account_identifier

    @property
    def credit_card_token(self):
        """Gets the credit_card_token of this CreateCreditCardUnregisterCriteria.  # noqa: E501

        Credit Card token  # noqa: E501

        :return: The credit_card_token of this CreateCreditCardUnregisterCriteria.  # noqa: E501
        :rtype: str
        """
        return self._credit_card_token

    @credit_card_token.setter
    def credit_card_token(self, credit_card_token):
        """Sets the credit_card_token of this CreateCreditCardUnregisterCriteria.

        Credit Card token  # noqa: E501

        :param credit_card_token: The credit_card_token of this CreateCreditCardUnregisterCriteria.  # noqa: E501
        :type: str
        """
        if self._configuration.client_side_validation and credit_card_token is None:
            raise ValueError("Invalid value for `credit_card_token`, must not be `None`")  # noqa: E501

        self._credit_card_token = credit_card_token

    @property
    def customer_identifier(self):
        """Gets the customer_identifier of this CreateCreditCardUnregisterCriteria.  # noqa: E501

        Customer Identifier  # noqa: E501

        :return: The customer_identifier of this CreateCreditCardUnregisterCriteria.  # noqa: E501
        :rtype: str
        """
        return self._customer_identifier

    @customer_identifier.setter
    def customer_identifier(self, customer_identifier):
        """Sets the customer_identifier of this CreateCreditCardUnregisterCriteria.

        Customer Identifier  # noqa: E501

        :param customer_identifier: The customer_identifier of this CreateCreditCardUnregisterCriteria.  # noqa: E501
        :type: str
        """
        if self._configuration.client_side_validation and customer_identifier is None:
            raise ValueError("Invalid value for `customer_identifier`, must not be `None`")  # noqa: E501

        self._customer_identifier = customer_identifier

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(CreateCreditCardUnregisterCriteria, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, CreateCreditCardUnregisterCriteria):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, CreateCreditCardUnregisterCriteria):
            return True

        return self.to_dict() != other.to_dict()
