# coding: utf-8

"""
    Tango Card RaaS API

    <5. Ordersp>Welcome to the RaaS&reg; API – with this RESTful API you can integrate a global reward or incentive program into your app or platform.<br /><br /> This console works in our Sandbox environment. To receive your own credentials or to ask questions, please contact us at <a href=\"mailto:devsupport@tangocard.com\">devsupport@tangocard.com</a>.  # noqa: E501

    OpenAPI spec version: 2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from tango_client.configuration import Configuration


class CreditCardUnregisterView(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'created_date': 'str',
        'message': 'str',
        'token': 'str'
    }

    attribute_map = {
        'created_date': 'createdDate',
        'message': 'message',
        'token': 'token'
    }

    def __init__(self, created_date=None, message=None, token=None, _configuration=None):  # noqa: E501
        """CreditCardUnregisterView - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._created_date = None
        self._message = None
        self._token = None
        self.discriminator = None

        self.created_date = created_date
        self.message = message
        self.token = token

    @property
    def created_date(self):
        """Gets the created_date of this CreditCardUnregisterView.  # noqa: E501

        Date the credit card was un-registered  # noqa: E501

        :return: The created_date of this CreditCardUnregisterView.  # noqa: E501
        :rtype: str
        """
        return self._created_date

    @created_date.setter
    def created_date(self, created_date):
        """Sets the created_date of this CreditCardUnregisterView.

        Date the credit card was un-registered  # noqa: E501

        :param created_date: The created_date of this CreditCardUnregisterView.  # noqa: E501
        :type: str
        """
        if self._configuration.client_side_validation and created_date is None:
            raise ValueError("Invalid value for `created_date`, must not be `None`")  # noqa: E501

        self._created_date = created_date

    @property
    def message(self):
        """Gets the message of this CreditCardUnregisterView.  # noqa: E501

        Friendly message that the credit card has been un-registered successfully  # noqa: E501

        :return: The message of this CreditCardUnregisterView.  # noqa: E501
        :rtype: str
        """
        return self._message

    @message.setter
    def message(self, message):
        """Sets the message of this CreditCardUnregisterView.

        Friendly message that the credit card has been un-registered successfully  # noqa: E501

        :param message: The message of this CreditCardUnregisterView.  # noqa: E501
        :type: str
        """
        if self._configuration.client_side_validation and message is None:
            raise ValueError("Invalid value for `message`, must not be `None`")  # noqa: E501

        self._message = message

    @property
    def token(self):
        """Gets the token of this CreditCardUnregisterView.  # noqa: E501

        Credit Card Unregister token identifier  # noqa: E501

        :return: The token of this CreditCardUnregisterView.  # noqa: E501
        :rtype: str
        """
        return self._token

    @token.setter
    def token(self, token):
        """Sets the token of this CreditCardUnregisterView.

        Credit Card Unregister token identifier  # noqa: E501

        :param token: The token of this CreditCardUnregisterView.  # noqa: E501
        :type: str
        """
        if self._configuration.client_side_validation and token is None:
            raise ValueError("Invalid value for `token`, must not be `None`")  # noqa: E501

        self._token = token

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(CreditCardUnregisterView, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, CreditCardUnregisterView):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, CreditCardUnregisterView):
            return True

        return self.to_dict() != other.to_dict()
