# coding: utf-8

"""
    Tango Card RaaS API

    <5. Ordersp>Welcome to the RaaS&reg; API – with this RESTful API you can integrate a global reward or incentive program into your app or platform.<br /><br /> This console works in our Sandbox environment. To receive your own credentials or to ask questions, please contact us at <a href=\"mailto:devsupport@tangocard.com\">devsupport@tangocard.com</a>.  # noqa: E501

    OpenAPI spec version: 2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from tango_client.configuration import Configuration


class OrderViewSummary(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'account_identifier': 'str',
        'amount_charged': 'MoneyView',
        'campaign': 'str',
        'created_at': 'str',
        'customer_identifier': 'str',
        'denomination': 'MoneyView',
        'email_subject': 'str',
        'external_ref_id': 'str',
        'message': 'str',
        'recipient': 'RecipientInfoView',
        'redemption_instructions': 'str',
        'reference_order_id': 'str',
        'reward': 'RewardView',
        'reward_name': 'str',
        'send_email': 'bool',
        'sender': 'SenderInfoView',
        'status': 'str',
        'utid': 'str'
    }

    attribute_map = {
        'account_identifier': 'accountIdentifier',
        'amount_charged': 'amountCharged',
        'campaign': 'campaign',
        'created_at': 'createdAt',
        'customer_identifier': 'customerIdentifier',
        'denomination': 'denomination',
        'email_subject': 'emailSubject',
        'external_ref_id': 'externalRefID',
        'message': 'message',
        'recipient': 'recipient',
        'redemption_instructions': 'redemptionInstructions',
        'reference_order_id': 'referenceOrderID',
        'reward': 'reward',
        'reward_name': 'rewardName',
        'send_email': 'sendEmail',
        'sender': 'sender',
        'status': 'status',
        'utid': 'utid'
    }

    def __init__(self, account_identifier=None, amount_charged=None, campaign=None, created_at=None, customer_identifier=None, denomination=None, email_subject=None, external_ref_id=None, message=None, recipient=None, redemption_instructions=None, reference_order_id=None, reward=None, reward_name=None, send_email=None, sender=None, status=None, utid=None, _configuration=None):  # noqa: E501
        """OrderViewSummary - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._account_identifier = None
        self._amount_charged = None
        self._campaign = None
        self._created_at = None
        self._customer_identifier = None
        self._denomination = None
        self._email_subject = None
        self._external_ref_id = None
        self._message = None
        self._recipient = None
        self._redemption_instructions = None
        self._reference_order_id = None
        self._reward = None
        self._reward_name = None
        self._send_email = None
        self._sender = None
        self._status = None
        self._utid = None
        self.discriminator = None

        self.account_identifier = account_identifier
        self.amount_charged = amount_charged
        self.campaign = campaign
        self.created_at = created_at
        self.customer_identifier = customer_identifier
        self.denomination = denomination
        self.email_subject = email_subject
        self.external_ref_id = external_ref_id
        self.message = message
        self.recipient = recipient
        if redemption_instructions is not None:
            self.redemption_instructions = redemption_instructions
        self.reference_order_id = reference_order_id
        self.reward = reward
        self.reward_name = reward_name
        self.send_email = send_email
        self.sender = sender
        self.status = status
        self.utid = utid

    @property
    def account_identifier(self):
        """Gets the account_identifier of this OrderViewSummary.  # noqa: E501

        Account Identifier  # noqa: E501

        :return: The account_identifier of this OrderViewSummary.  # noqa: E501
        :rtype: str
        """
        return self._account_identifier

    @account_identifier.setter
    def account_identifier(self, account_identifier):
        """Sets the account_identifier of this OrderViewSummary.

        Account Identifier  # noqa: E501

        :param account_identifier: The account_identifier of this OrderViewSummary.  # noqa: E501
        :type: str
        """
        if self._configuration.client_side_validation and account_identifier is None:
            raise ValueError("Invalid value for `account_identifier`, must not be `None`")  # noqa: E501

        self._account_identifier = account_identifier

    @property
    def amount_charged(self):
        """Gets the amount_charged of this OrderViewSummary.  # noqa: E501

        Amount Charged  # noqa: E501

        :return: The amount_charged of this OrderViewSummary.  # noqa: E501
        :rtype: MoneyView
        """
        return self._amount_charged

    @amount_charged.setter
    def amount_charged(self, amount_charged):
        """Sets the amount_charged of this OrderViewSummary.

        Amount Charged  # noqa: E501

        :param amount_charged: The amount_charged of this OrderViewSummary.  # noqa: E501
        :type: MoneyView
        """
        if self._configuration.client_side_validation and amount_charged is None:
            raise ValueError("Invalid value for `amount_charged`, must not be `None`")  # noqa: E501

        self._amount_charged = amount_charged

    @property
    def campaign(self):
        """Gets the campaign of this OrderViewSummary.  # noqa: E501

        Reward Campaign  # noqa: E501

        :return: The campaign of this OrderViewSummary.  # noqa: E501
        :rtype: str
        """
        return self._campaign

    @campaign.setter
    def campaign(self, campaign):
        """Sets the campaign of this OrderViewSummary.

        Reward Campaign  # noqa: E501

        :param campaign: The campaign of this OrderViewSummary.  # noqa: E501
        :type: str
        """
        if self._configuration.client_side_validation and campaign is None:
            raise ValueError("Invalid value for `campaign`, must not be `None`")  # noqa: E501

        self._campaign = campaign

    @property
    def created_at(self):
        """Gets the created_at of this OrderViewSummary.  # noqa: E501

        Created Date  # noqa: E501

        :return: The created_at of this OrderViewSummary.  # noqa: E501
        :rtype: str
        """
        return self._created_at

    @created_at.setter
    def created_at(self, created_at):
        """Sets the created_at of this OrderViewSummary.

        Created Date  # noqa: E501

        :param created_at: The created_at of this OrderViewSummary.  # noqa: E501
        :type: str
        """
        if self._configuration.client_side_validation and created_at is None:
            raise ValueError("Invalid value for `created_at`, must not be `None`")  # noqa: E501

        self._created_at = created_at

    @property
    def customer_identifier(self):
        """Gets the customer_identifier of this OrderViewSummary.  # noqa: E501

        Customer Identifier  # noqa: E501

        :return: The customer_identifier of this OrderViewSummary.  # noqa: E501
        :rtype: str
        """
        return self._customer_identifier

    @customer_identifier.setter
    def customer_identifier(self, customer_identifier):
        """Sets the customer_identifier of this OrderViewSummary.

        Customer Identifier  # noqa: E501

        :param customer_identifier: The customer_identifier of this OrderViewSummary.  # noqa: E501
        :type: str
        """
        if self._configuration.client_side_validation and customer_identifier is None:
            raise ValueError("Invalid value for `customer_identifier`, must not be `None`")  # noqa: E501

        self._customer_identifier = customer_identifier

    @property
    def denomination(self):
        """Gets the denomination of this OrderViewSummary.  # noqa: E501

        Denomination  # noqa: E501

        :return: The denomination of this OrderViewSummary.  # noqa: E501
        :rtype: MoneyView
        """
        return self._denomination

    @denomination.setter
    def denomination(self, denomination):
        """Sets the denomination of this OrderViewSummary.

        Denomination  # noqa: E501

        :param denomination: The denomination of this OrderViewSummary.  # noqa: E501
        :type: MoneyView
        """
        if self._configuration.client_side_validation and denomination is None:
            raise ValueError("Invalid value for `denomination`, must not be `None`")  # noqa: E501

        self._denomination = denomination

    @property
    def email_subject(self):
        """Gets the email_subject of this OrderViewSummary.  # noqa: E501

        Email Subject  # noqa: E501

        :return: The email_subject of this OrderViewSummary.  # noqa: E501
        :rtype: str
        """
        return self._email_subject

    @email_subject.setter
    def email_subject(self, email_subject):
        """Sets the email_subject of this OrderViewSummary.

        Email Subject  # noqa: E501

        :param email_subject: The email_subject of this OrderViewSummary.  # noqa: E501
        :type: str
        """
        if self._configuration.client_side_validation and email_subject is None:
            raise ValueError("Invalid value for `email_subject`, must not be `None`")  # noqa: E501

        self._email_subject = email_subject

    @property
    def external_ref_id(self):
        """Gets the external_ref_id of this OrderViewSummary.  # noqa: E501

        External Reference ID  # noqa: E501

        :return: The external_ref_id of this OrderViewSummary.  # noqa: E501
        :rtype: str
        """
        return self._external_ref_id

    @external_ref_id.setter
    def external_ref_id(self, external_ref_id):
        """Sets the external_ref_id of this OrderViewSummary.

        External Reference ID  # noqa: E501

        :param external_ref_id: The external_ref_id of this OrderViewSummary.  # noqa: E501
        :type: str
        """
        if self._configuration.client_side_validation and external_ref_id is None:
            raise ValueError("Invalid value for `external_ref_id`, must not be `None`")  # noqa: E501

        self._external_ref_id = external_ref_id

    @property
    def message(self):
        """Gets the message of this OrderViewSummary.  # noqa: E501

        Email Message  # noqa: E501

        :return: The message of this OrderViewSummary.  # noqa: E501
        :rtype: str
        """
        return self._message

    @message.setter
    def message(self, message):
        """Sets the message of this OrderViewSummary.

        Email Message  # noqa: E501

        :param message: The message of this OrderViewSummary.  # noqa: E501
        :type: str
        """
        if self._configuration.client_side_validation and message is None:
            raise ValueError("Invalid value for `message`, must not be `None`")  # noqa: E501

        self._message = message

    @property
    def recipient(self):
        """Gets the recipient of this OrderViewSummary.  # noqa: E501

        Recipient Details  # noqa: E501

        :return: The recipient of this OrderViewSummary.  # noqa: E501
        :rtype: RecipientInfoView
        """
        return self._recipient

    @recipient.setter
    def recipient(self, recipient):
        """Sets the recipient of this OrderViewSummary.

        Recipient Details  # noqa: E501

        :param recipient: The recipient of this OrderViewSummary.  # noqa: E501
        :type: RecipientInfoView
        """
        if self._configuration.client_side_validation and recipient is None:
            raise ValueError("Invalid value for `recipient`, must not be `None`")  # noqa: E501

        self._recipient = recipient

    @property
    def redemption_instructions(self):
        """Gets the redemption_instructions of this OrderViewSummary.  # noqa: E501

        Redemption Instructions  # noqa: E501

        :return: The redemption_instructions of this OrderViewSummary.  # noqa: E501
        :rtype: str
        """
        return self._redemption_instructions

    @redemption_instructions.setter
    def redemption_instructions(self, redemption_instructions):
        """Sets the redemption_instructions of this OrderViewSummary.

        Redemption Instructions  # noqa: E501

        :param redemption_instructions: The redemption_instructions of this OrderViewSummary.  # noqa: E501
        :type: str
        """

        self._redemption_instructions = redemption_instructions

    @property
    def reference_order_id(self):
        """Gets the reference_order_id of this OrderViewSummary.  # noqa: E501

        Reference Order ID  # noqa: E501

        :return: The reference_order_id of this OrderViewSummary.  # noqa: E501
        :rtype: str
        """
        return self._reference_order_id

    @reference_order_id.setter
    def reference_order_id(self, reference_order_id):
        """Sets the reference_order_id of this OrderViewSummary.

        Reference Order ID  # noqa: E501

        :param reference_order_id: The reference_order_id of this OrderViewSummary.  # noqa: E501
        :type: str
        """
        if self._configuration.client_side_validation and reference_order_id is None:
            raise ValueError("Invalid value for `reference_order_id`, must not be `None`")  # noqa: E501

        self._reference_order_id = reference_order_id

    @property
    def reward(self):
        """Gets the reward of this OrderViewSummary.  # noqa: E501

        The Reward  # noqa: E501

        :return: The reward of this OrderViewSummary.  # noqa: E501
        :rtype: RewardView
        """
        return self._reward

    @reward.setter
    def reward(self, reward):
        """Sets the reward of this OrderViewSummary.

        The Reward  # noqa: E501

        :param reward: The reward of this OrderViewSummary.  # noqa: E501
        :type: RewardView
        """
        if self._configuration.client_side_validation and reward is None:
            raise ValueError("Invalid value for `reward`, must not be `None`")  # noqa: E501

        self._reward = reward

    @property
    def reward_name(self):
        """Gets the reward_name of this OrderViewSummary.  # noqa: E501

        Reward Name  # noqa: E501

        :return: The reward_name of this OrderViewSummary.  # noqa: E501
        :rtype: str
        """
        return self._reward_name

    @reward_name.setter
    def reward_name(self, reward_name):
        """Sets the reward_name of this OrderViewSummary.

        Reward Name  # noqa: E501

        :param reward_name: The reward_name of this OrderViewSummary.  # noqa: E501
        :type: str
        """
        if self._configuration.client_side_validation and reward_name is None:
            raise ValueError("Invalid value for `reward_name`, must not be `None`")  # noqa: E501

        self._reward_name = reward_name

    @property
    def send_email(self):
        """Gets the send_email of this OrderViewSummary.  # noqa: E501

        Send Email?  # noqa: E501

        :return: The send_email of this OrderViewSummary.  # noqa: E501
        :rtype: bool
        """
        return self._send_email

    @send_email.setter
    def send_email(self, send_email):
        """Sets the send_email of this OrderViewSummary.

        Send Email?  # noqa: E501

        :param send_email: The send_email of this OrderViewSummary.  # noqa: E501
        :type: bool
        """
        if self._configuration.client_side_validation and send_email is None:
            raise ValueError("Invalid value for `send_email`, must not be `None`")  # noqa: E501

        self._send_email = send_email

    @property
    def sender(self):
        """Gets the sender of this OrderViewSummary.  # noqa: E501

        Sender Details  # noqa: E501

        :return: The sender of this OrderViewSummary.  # noqa: E501
        :rtype: SenderInfoView
        """
        return self._sender

    @sender.setter
    def sender(self, sender):
        """Sets the sender of this OrderViewSummary.

        Sender Details  # noqa: E501

        :param sender: The sender of this OrderViewSummary.  # noqa: E501
        :type: SenderInfoView
        """
        if self._configuration.client_side_validation and sender is None:
            raise ValueError("Invalid value for `sender`, must not be `None`")  # noqa: E501

        self._sender = sender

    @property
    def status(self):
        """Gets the status of this OrderViewSummary.  # noqa: E501

        Reward Status  # noqa: E501

        :return: The status of this OrderViewSummary.  # noqa: E501
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this OrderViewSummary.

        Reward Status  # noqa: E501

        :param status: The status of this OrderViewSummary.  # noqa: E501
        :type: str
        """
        if self._configuration.client_side_validation and status is None:
            raise ValueError("Invalid value for `status`, must not be `None`")  # noqa: E501

        self._status = status

    @property
    def utid(self):
        """Gets the utid of this OrderViewSummary.  # noqa: E501

        Utid - Unique Tango Card ID.  # noqa: E501

        :return: The utid of this OrderViewSummary.  # noqa: E501
        :rtype: str
        """
        return self._utid

    @utid.setter
    def utid(self, utid):
        """Sets the utid of this OrderViewSummary.

        Utid - Unique Tango Card ID.  # noqa: E501

        :param utid: The utid of this OrderViewSummary.  # noqa: E501
        :type: str
        """
        if self._configuration.client_side_validation and utid is None:
            raise ValueError("Invalid value for `utid`, must not be `None`")  # noqa: E501

        self._utid = utid

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(OrderViewSummary, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, OrderViewSummary):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, OrderViewSummary):
            return True

        return self.to_dict() != other.to_dict()
