# coding: utf-8

"""
    Tango Card RaaS API

    <p>Welcome to the RaaS&reg; API – with this RESTful API you can integrate a global reward or incentive program into your app or platform.<br /><br /> This console works in our Sandbox environment. To receive your own credentials or to ask questions, please contact us at <a href=\"mailto:devsupport@tangocard.com\">devsupport@tangocard.com</a>.  # noqa: E501

    OpenAPI spec version: 2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from tango_client.configuration import Configuration


class OrderListView(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'orders': 'list[OrderListItemView]',
        'page': 'PageView'
    }

    attribute_map = {
        'orders': 'orders',
        'page': 'page'
    }

    def __init__(self, orders=None, page=None, _configuration=None):  # noqa: E501
        """OrderListView - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._orders = None
        self._page = None
        self.discriminator = None

        self.orders = orders
        self.page = page

    @property
    def orders(self):
        """Gets the orders of this OrderListView.  # noqa: E501

        Order elements for the current page  # noqa: E501

        :return: The orders of this OrderListView.  # noqa: E501
        :rtype: list[OrderListItemView]
        """
        return self._orders

    @orders.setter
    def orders(self, orders):
        """Sets the orders of this OrderListView.

        Order elements for the current page  # noqa: E501

        :param orders: The orders of this OrderListView.  # noqa: E501
        :type: list[OrderListItemView]
        """
        if self._configuration.client_side_validation and orders is None:
            raise ValueError("Invalid value for `orders`, must not be `None`")  # noqa: E501

        self._orders = orders

    @property
    def page(self):
        """Gets the page of this OrderListView.  # noqa: E501

        Page data for matching orders  # noqa: E501

        :return: The page of this OrderListView.  # noqa: E501
        :rtype: PageView
        """
        return self._page

    @page.setter
    def page(self, page):
        """Sets the page of this OrderListView.

        Page data for matching orders  # noqa: E501

        :param page: The page of this OrderListView.  # noqa: E501
        :type: PageView
        """
        if self._configuration.client_side_validation and page is None:
            raise ValueError("Invalid value for `page`, must not be `None`")  # noqa: E501

        self._page = page

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(OrderListView, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, OrderListView):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, OrderListView):
            return True

        return self.to_dict() != other.to_dict()
