# coding: utf-8

"""
    Tango Card RaaS API

    <5. Ordersp>Welcome to the RaaS&reg; API – with this RESTful API you can integrate a global reward or incentive program into your app or platform.<br /><br /> This console works in our Sandbox environment. To receive your own credentials or to ask questions, please contact us at <a href=\"mailto:devsupport@tangocard.com\">devsupport@tangocard.com</a>.  # noqa: E501

    OpenAPI spec version: 2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from tango_client.configuration import Configuration


class ResendView(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'created_at': 'str',
        'email': 'str',
        'id': 'int',
        'legacy_id': 'str'
    }

    attribute_map = {
        'created_at': 'createdAt',
        'email': 'email',
        'id': 'id',
        'legacy_id': 'legacyId'
    }

    def __init__(self, created_at=None, email=None, id=None, legacy_id=None, _configuration=None):  # noqa: E501
        """ResendView - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._created_at = None
        self._email = None
        self._id = None
        self._legacy_id = None
        self.discriminator = None

        self.created_at = created_at
        self.email = email
        self.id = id
        if legacy_id is not None:
            self.legacy_id = legacy_id

    @property
    def created_at(self):
        """Gets the created_at of this ResendView.  # noqa: E501

        Created Date  # noqa: E501

        :return: The created_at of this ResendView.  # noqa: E501
        :rtype: str
        """
        return self._created_at

    @created_at.setter
    def created_at(self, created_at):
        """Sets the created_at of this ResendView.

        Created Date  # noqa: E501

        :param created_at: The created_at of this ResendView.  # noqa: E501
        :type: str
        """
        if self._configuration.client_side_validation and created_at is None:
            raise ValueError("Invalid value for `created_at`, must not be `None`")  # noqa: E501

        self._created_at = created_at

    @property
    def email(self):
        """Gets the email of this ResendView.  # noqa: E501

        Email address that the resend was sent to  # noqa: E501

        :return: The email of this ResendView.  # noqa: E501
        :rtype: str
        """
        return self._email

    @email.setter
    def email(self, email):
        """Sets the email of this ResendView.

        Email address that the resend was sent to  # noqa: E501

        :param email: The email of this ResendView.  # noqa: E501
        :type: str
        """
        if self._configuration.client_side_validation and email is None:
            raise ValueError("Invalid value for `email`, must not be `None`")  # noqa: E501

        self._email = email

    @property
    def id(self):
        """Gets the id of this ResendView.  # noqa: E501

        ID  # noqa: E501

        :return: The id of this ResendView.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this ResendView.

        ID  # noqa: E501

        :param id: The id of this ResendView.  # noqa: E501
        :type: int
        """
        if self._configuration.client_side_validation and id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    @property
    def legacy_id(self):
        """Gets the legacy_id of this ResendView.  # noqa: E501

        Legacy ID (only when resending v1 orders)  # noqa: E501

        :return: The legacy_id of this ResendView.  # noqa: E501
        :rtype: str
        """
        return self._legacy_id

    @legacy_id.setter
    def legacy_id(self, legacy_id):
        """Sets the legacy_id of this ResendView.

        Legacy ID (only when resending v1 orders)  # noqa: E501

        :param legacy_id: The legacy_id of this ResendView.  # noqa: E501
        :type: str
        """

        self._legacy_id = legacy_id

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ResendView, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ResendView):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, ResendView):
            return True

        return self.to_dict() != other.to_dict()
